## Assignment B3
#### Hair and Eye Colour of Students 

###### By Laura Simonson 60858685

The Hair and Eye Colour shiny app was designed to show the hair and eye colours of students at the University of Delaware, using the HairEyeColor dataset. 
The user of this app is able to filter by hair colour, eye colour and gender of interest using the select options on the left-hand side of the app. A corresponding bar graph will be produced based on the user's input, which will show how many students have each hair and eye colour combination. A summary sentence underneath the graph informs the user of how many total students have the hair colour, eye colour and gender they have selected. 

[Here is a link to the running shiny app](https://lsimonson.shinyapps.io/assigmentb3/)

The HairEyeColour Dataset used in this app was collected by Snee in 1974 and Updated by Friendly in 1992. 

[Here is a link to the R Documentation for this dataset](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/HairEyeColor.html)
